# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SteamProphet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('steamID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('owners', models.PositiveIntegerField(default=0)),
                ('ownerVariance', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SteamProphet.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pick',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SteamProphet.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together=set([('player', 'game')]),
        ),
    ]
