# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0002_auto_20170518_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='steamID',
            new_name='appID',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='ownerVariance',
            new_name='ownersVariance',
        ),
    ]
