# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0003_auto_20170518_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
