# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0004_auto_20170518_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='joker',
            field=models.BooleanField(default=False),
        ),
    ]
