# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0005_pick_joker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='owners',
            new_name='players',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='ownersVariance',
            new_name='playersVariance',
        ),
    ]
