# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0007_auto_20170521_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
