# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 07:52
from __future__ import unicode_literals

from datetime import date

from django.db import migrations

def setGameWeek(apps, _):
    Game = apps.get_model('SteamProphet', 'Game')
    startdate = date(year=2017, month=6, day=12)
    enddate = date(year=2017, month=6, day=18)
    Game.objects.filter(releaseDate__range=(startdate, enddate)).update(week=2)

class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0008_game_week'),
    ]

    operations = [
        migrations.RunPython(setGameWeek)
    ]
