# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0009_set_game_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='fallback',
            field=models.BooleanField(default=False),
        ),
    ]
