# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0010_pick_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='matured',
            field=models.BooleanField(default=False),
        ),
    ]
