# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0011_game_matured'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
