# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0012_game_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
