# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0014_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingPeriod',
            fields=[
                ('week', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
