# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SteamProphet', '0015_votingperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='player',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
