# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 16:23
from __future__ import unicode_literals

from django.db import migrations


def createUsersForPlayers(apps, _):
    User = apps.get_model('auth', 'User')
    Player = apps.get_model('SteamProphet', 'Player')
    for player in Player.objects.all():
        player.user = User.objects.get_or_create(username=player.name)[0]
        player.save()

class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0017_player_user'),
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(createUsersForPlayers)
    ]
