# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0020_auto_20170719_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('week', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
