# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0022_rename_old_week_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.ManyToManyField(to='SteamProphet.Week'),
        ),
        migrations.AddField(
            model_name='pick',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SteamProphet.Week'),
        ),
        migrations.AddField(
            model_name='votingperiod',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SteamProphet.Week'),
        ),
    ]
