# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:18
from __future__ import unicode_literals

from django.db import migrations


def associate_games_to_week(apps, _):
    Game = apps.get_model('SteamProphet', 'Game')
    Week = apps.get_model('SteamProphet', 'Week')
    for game in Game.objects.all():
        game.week.add(Week.objects.get_or_create(week=game.week_old)[0])
        game.save()


def associate_picks_to_week(apps, _):
    Pick = apps.get_model('SteamProphet', 'Pick')
    Week = apps.get_model('SteamProphet', 'Week')
    for pick in Pick.objects.all():
        pick.week = Week.objects.get_or_create(week=pick.game.week_old)[0]
        pick.save()


def associate_voting_periods_to_week(apps, _):
    VotingPeriod = apps.get_model('SteamProphet', 'VotingPeriod')
    Week = apps.get_model('SteamProphet', 'Week')
    for votingPeriod in VotingPeriod.objects.all():
        votingPeriod.week = Week.objects.get_or_create(week=votingPeriod.week_old)[0]
        votingPeriod.save()


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0023_add_week_relationships'),
    ]

    operations = [
        migrations.RunPython(associate_games_to_week),
        migrations.RunPython(associate_picks_to_week),
        migrations.RunPython(associate_voting_periods_to_week)
    ]
