# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SteamProphet', '0024_auto_20170724_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='week_old',
        ),
        migrations.RemoveField(
            model_name='votingperiod',
            name='week_old',
        ),
        migrations.AlterField(
            model_name='pick',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SteamProphet.Week'),
        ),
        migrations.AlterField(
            model_name='votingperiod',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SteamProphet.Week'),
        ),
        migrations.AddField(
            model_name='votingperiod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
